from enum import Enum
# ---------- Indices ----------
LIFEPOINTS = 0
HAPPINESS = 1
HUNGER = 2
HEALTH = 3
WEIGHT = 4
POOP = 5

# ---------- Variable limits ----------
LIFEPOINTS_MAX = 100
HAPPINESS_MAX = 100
HUNGER_MAX = 100
HEALTH_MAX = 100
WEIGHT_MAX = 100
POOP_MAX = 20
VARIABLES_MAX = [LIFEPOINTS_MAX, HAPPINESS_MAX,
                 HUNGER_MAX, HEALTH_MAX, WEIGHT_MAX, POOP_MAX]

LIFEPOINTS_MIN = 0
HAPPINESS_MIN = 0
HUNGER_MIN = 0
HEALTH_MIN = 0
WEIGHT_MIN = 0
POOP_MIN = 0
VARIABLES_MIN = [LIFEPOINTS_MIN, HAPPINESS_MIN,
                 HUNGER_MIN, HEALTH_MIN, WEIGHT_MIN, POOP_MIN]

# ---------- Initial Variables ----------
LIFEPOINTS_INIT = 100
HAPPINESS_INIT = 80
HUNGER_INIT = 0
HEALTH_INIT = 80
WEIGHT_INIT = 30
POOP_INIT = 0
VARIABLES_INIT = [LIFEPOINTS_INIT, HAPPINESS_INIT,
                  HUNGER_INIT, HEALTH_INIT, WEIGHT_INIT, POOP_INIT]

# ---------- Pet types ----------


class PetTypes(Enum):
    CAT = 0
