# ---------- Variable limits ----------
    = 100
LIFEPOINTS_INIT =
HAPPINESS_INIT =
HUNGER_INIT =
HEALTH_INIT =
WEIGHT_INIT =
POOP_INIT = 20

VARIABLE_MIN = 0
LIFEPOINTS_MIN = VARIABLE_MIN
HAPPINESS_MIN = VARIABLE_MIN
HUNGER_MIN = VARIABLE_MIN
HEALTH_MIN = VARIABLE_MIN
WEIGHT_MIN = VARIABLE_MIN
POOP_MIN = VARIABLE_MIN

# ---------- Initial Variables ----------
LIFEPOINTS_INIT = 100
HAPPINESS_INIT = 80
HUNGER_INIT = 0
HEALTH_INIT = 80
WEIGHT_INIT = 30
POOP_INIT = 0
